### ISSUE TITLE
rss/atom feed

### ISSUE THREAD

**Issue by Sertonix** [chimera-linux/chimera-linux.github.io#19]
It would be nice to have an rss or atom feed for the news on the page so people can stay up to date without manually viewing the site every time.
There seems to be a [jekyll-feed](https://github.com/jekyll/jekyll-feed) plugin for that purpose.

**Comment by q66** [comment]
https://github.com/chimera-linux/chimera-linux.github.io/commit/fa5397e16c7b617e815c07f20454ca10a575621e
